# netra_backend/config.py
import os
from dataclasses import dataclass
from typing import List
@dataclass
class OpenC3Config:
    scope: str
    api_hostname: str
    api_port: str
    api_password: str
    packets_tlm: List[str]
    packets_cmd: List[str]
    items_to_stream: List[str]
def get_openc3_config() -> OpenC3Config:
    # Mirrors your env usage
    scope = os.getenv("OPENC3_SCOPE", "DEFAULT")
    hostname = os.getenv("OPENC3_API_HOSTNAME", "127.0.0.1")
    port = os.getenv("OPENC3_API_PORT", "2900")
    password = os.getenv("OPENC3_API_PASSWORD", "mos12345")
    # Your packet lists – copy-pasted from your script
    packets_tlm = [
        "RAW__TLM__EMULATOR__HEALTH_ADCS_CMD_ATTITUDE_ANGLE",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_CONS_CURRENT",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_CSS_VECTOR",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_CURRENT_STATE",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_EST_ATTITUDE_ANGLE",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_EST_GYRO_BIAS",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_EST_INNOV",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_EST_RATES",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_FINE_EST_ANG_RATES",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_FSS_VECTOR",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_IGRF_MOD_VEC",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_MAG_FIELD_VEC",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_MEAS_RW_SPEED",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_MGTRQR_CMD",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_MISC_CURRENT",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_NADAR_VEC",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_POS_ERR",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_POS_LLH",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_QUAT_ERR_VEC",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_RATE_SENSOR_MEASURE",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_RATE_SENSOR_TEMP",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_RAW_CSS",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_RAW_FSS_SNS",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_RAW_MAG_MEASURE",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_RAW_NADAR_SNS",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_RAW_RATE_SENSOR_MEASURE",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_RAW_STAR_TRKR_MEAS",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_RW_CURRENT",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_RW_SPEED_CMD",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_SAT_POS_ECEF_FRAME",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_SAT_POS_ECI_FRAME",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_SAT_VEL_ECEF_FRAME",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_SAT_VEL_ECI_FRAME",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_SENSOR_CURRENT",
        "RAW__TLM__EMULATOR__HEALTH_ADCS_TEMP",
        "RAW__TLM__EMULATOR__HEALTH_COMMS_S",
        "RAW__TLM__EMULATOR__HEALTH_COMMS_UHF",
        "RAW__TLM__EMULATOR__HEALTH_COMMS_XBAND1",
        "RAW__TLM__EMULATOR__HEALTH_EPS",
        "RAW__TLM__EMULATOR__HEALTH_EPS_GET_SES_TEMP_HM",
        "RAW__TLM__EMULATOR__HEALTH_ERROR_HANDLER",
        "RAW__TLM__EMULATOR__HEALTH_ES_DATA",
        "RAW__TLM__EMULATOR__HEALTH_FDIR_DATA_QUEUE_0",
        "RAW__TLM__EMULATOR__HEALTH_FDIR_DATA_QUEUE_1",
        "RAW__TLM__EMULATOR__HEALTH_FDIR_DATA_QUEUE_2",
        "RAW__TLM__EMULATOR__HEALTH_GNSS_DATA",
        "RAW__TLM__EMULATOR__HEALTH_OBC",
        "RAW__TLM__EMULATOR__HEALTH_PS_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_DT_EDGE_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_DT_PS_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_ES_SSD0_HEAT_COIL_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_ES_SSD1_HEAT_COIL_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_HSC_EDGE_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_HSC_ES_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_HSC_NIC_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_HSC_PS1_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_HSC_PS2_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_HSC_PS_BRD_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_HSC_PS_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_HSC_PS_SSD_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_PSM_ES_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_PSM_NIC_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_PSM_OBC_1_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_PSM_OBC_2_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_PSM_PS_BRD_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_PSM_PS_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_PS_SSD0_HEAT_COIL_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_PS_SSD1_HEAT_COIL_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_PS_SSD2_HEAT_COIL_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_PS_SSD3_HEAT_COIL_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_TEMP_ES_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_TEMP_ES_SSD0_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_TEMP_ES_SSD1_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_TEMP_GPS_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_TEMP_NIC_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_TEMP_OBC_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_TEMP_PS_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_TEMP_PS_SSD0_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_TEMP_PS_SSD1_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_TEMP_PS_SSD2_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_TEMP_PS_SSD3_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_TEMP_SPB01_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_TEMP_SPE01_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_TEMP_SPE02_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_TEMP_SPW01_DATA",
        "RAW__TLM__EMULATOR__HEALTH_SENSORS_TEMP_SPW02_DATA",
        "RAW__TLM__EMULATOR__HEALTH_THRUSTER_DATA_QUEUE_0",
        "RAW__TLM__EMULATOR__HEALTH_THRUSTER_DATA_QUEUE_1",
        "DECOM__TLM__EMULATOR__TM_547__FORMATTED",
        "DECOM__TLM__EMULATOR__TM_CONOPS_SCH_LUT_RUN_CTRL__FORMATTED",
        "DECOM__TLM__EMULATOR__TM_DEFERRED_STORAGE__FORMATTED",
        "DECOM__TLM__EMULATOR__OBC_581_TM_GET_CUR_TIME__FORMATTED",
    ]
    packets_cmd = [
        "DECOM__CMD__EMULATOR__OBC_581_TC_GET_CUR_TIME",
        "DECOM__CMD__EMULATOR__OBC_500_TC_GET_PROC_UTIL_INFO",
        "DECOM__CMD__EMULATOR__1021_TC_EXOTRAIL_GET_SYS_INFO",
    ]
    items_to_stream: list[str] = []  # optional
    return OpenC3Config(
        scope=scope,
        api_hostname=hostname,
        api_port=port,
        api_password=password,
        packets_tlm=packets_tlm,
        packets_cmd=packets_cmd,
        items_to_stream=items_to_stream,
    )