{
 "title": "EPS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Solar Panel Currents",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  $__timeGroup(\"Timestamp\"::timestamp, $__interval) AS time,\n  avg(\"Solar_Panel_Current_A_01\") AS sp_01,\n  avg(\"Solar_Panel_Current_A_02\") AS sp_02,\n  avg(\"Solar_Panel_Current_A_03\") AS sp_03,\n  avg(\"Solar_Panel_Current_A_04\") AS sp_04,\n  avg(\"Solar_Panel_Current_A_05\") AS sp_05,\n  avg(\"Solar_Panel_Current_A_06\") AS sp_06,\n  avg(\"Solar_Panel_Current_A_07\") AS sp_07,\n  avg(\"Solar_Panel_Current_A_08\") AS sp_08,\n  avg(\"Solar_Panel_Current_A_09\") AS sp_09\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nGROUP BY\n  time\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Total Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Battery_Total_Voltage_V\"\nFROM \"HEALTH_EPS\"\nWHERE $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Total Battery Current",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Battery_Total_Current_A\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Solat Temp Sensor",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Solar_Temp_C_01\",\n  \"Solar_Temp_C_02\",\n  \"Solar_Temp_C_03\",\n  \"Solar_Temp_C_04\",\n  \"Solar_Temp_C_05\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Power Generation Vs Consumption",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Total_Power_Generated_Wh\",\n  \"Total_Power_Consumed_Wh\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Reset Counts",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"OBC_Reset_Count\",\n  \"Output_Channel_Reset_Count\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Battery Temp",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Battery_Temp_C_01\",\n  \"Battery_Temp_C_02\",\n  \"Battery_Temp_C_03\",\n  \"Battery_Temp_C_04\",\n  \"Battery_Temp_C_05\",\n  \"Battery_Temp_C_06\",\n  \"Battery_Temp_C_07\",\n  \"Battery_Temp_C_08\",\n  \"Battery_Temp_C_09\",\n  \"Battery_Temp_C_10\",\n  \"Battery_Temp_C_11\",\n  \"Battery_Temp_C_12\",\n  \"Battery_Temp_C_13\",\n  \"Battery_Temp_C_14\",\n  \"Battery_Temp_C_15\",\n  \"Battery_Temp_C_16\",\n  \"Battery_Temp_C_17\",\n  \"Battery_Temp_C_18\",\n  \"Battery_Temp_C_19\",\n  \"Battery_Temp_C_20\",\n  \"Battery_Temp_C_21\",\n  \"Battery_Temp_C_22\",\n  \"Battery_Temp_C_23\",\n  \"Battery_Temp_C_24\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Output Convertor Voltages",
   "type": "stat",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Volts" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Output_Converter_Voltage_V_01\",\n  \"Output_Converter_Voltage_V_02\",\n  \"Output_Converter_Voltage_V_03\",\n  \"Output_Converter_Voltage_V_04\",\n  \"Output_Converter_Voltage_V_05\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Hold and Release Module",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Valid_HRM\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "OBC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Valid_HRM\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Payload Server",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Valid_PL_SERVER\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "ADCS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Valid_ADCS\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "UHF",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Valid_UHF\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "SES_A",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT \"Valid_SES_A\" FROM \"HEALTH_EPS\" LIMIT 1"
    }
   ]
  },
  {
   "title": "UHF_BURN_WIRE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Valid_UHF_BURN_WIRE\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Power supply channel currents",
   "type": "bargauge",
   "gridPos": { "h": 25, "w": 14, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"PS_Current_A_OBC_00_00\",\n  \"PS_Current_A_OBC_01_01\",\n  \"PS_Current_A_PL_8_02_02\",\n  \"PS_Current_A_ADCS_03_03\",\n  \"PS_Current_A_THRUSTER_04_04\",\n  \"PS_Current_A_THRUSTER_05_05\",\n  \"PS_Current_A_THRUSTER_HEATER_06_06\",\n  \"PS_Current_A_UHF_07_07\",\n  \"PS_Current_A_SBAND_08_08\",\n  \"PS_Current_A_XBAND_2_09_09\",\n  \"PS_Current_A_XBAND_10_10\",\n  \"PS_Current_A_PL_1_11_11\",\n  \"PS_Current_A_PL_2_HEATER_PL_3_HEATER_12\",\n  \"PS_Current_A_HRM_15_41\",\n  \"PS_Current_A_PL_7_51_51\",\n  \"PS_Current_A_PL_6_HEATER_50_50\",\n  \"PS_Current_A_HRM_22_48\",\n  \"PS_Current_A_HRM_21_47\",\n  \"PS_Current_A_HRM_18_44\",\n  \"PS_Current_A_HRM_16_16\",\n  \"PS_Current_A_HRM_19_19\",\n  \"PS_Current_A_HRM_17_17\",\n  \"PS_Current_A_PL_8_02_28\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Battery Mode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Battery_Mode\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"UHF_Antenna_Release\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Primary_HDRM_Release\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Secondary_HDRM_Release\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Solar Panel Voltages",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Solar_Panel_Voltage_V_01\",\n  \"Solar_Panel_Voltage_V_02\",\n  \"Solar_Panel_Voltage_V_03\",\n  \"Solar_Panel_Voltage_V_04\",\n  \"Solar_Panel_Voltage_V_05\",\n  \"Solar_Panel_Voltage_V_06\",\n  \"Solar_Panel_Voltage_V_07\"\nFROM\n  \"HEALTH_EPS\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time\n"
    }
   ]
  }
 ]
}