{
 "title": "telemetry_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "MGTRQR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\r\n  \"Epoch_Time_Human\"::timestamp AS time,\r\n  \"MGTRQR_Cmd_X\",\r\n  \"MGTRQR_Cmd_Y\",\r\n  \"MGTRQR_Cmd_Z\"\r\nFROM \"HEALTH_ADCS_MGTRQR_CMD\"\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "Nadir vectors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\r\n  \"Epoch_Time_Human\"::timestamp AS time,\r\n  \"NADAR_Vector_X\",\r\n  \"NADAR_Vector_Y\",\r\n  \"NADAR_Vector_Z\"\r\nFROM \"HEALTH_ADCS_NADAR_VEC\"\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "SENSORS DATA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\r\n  \"temp_epoch_time\"::timestamp AS time,\r\n  \"temperature\"\r\nFROM \"HEALTH_SENSORS_TEMP_PS_DATA\"\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "POS_LLH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\r\n  \"Epoch_Time_Human\"::timestamp AS time,\r\n  \"Geocentric_longitude\",\r\n  \"Geocentric_latitude\",\r\n  \"Geocentric_altitude\"\r\nFROM \"HEALTH_ADCS_POS_LLH\"\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "RW_SPEED_CMD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\r\n  \"Epoch_Time_Human\"::timestamp AS time,\r\n  \"Command_Wheel_Speed_1\",\r\n  \"Command_Wheel_Speed_2\",\r\n  \"Command_Wheel_Speed_3\"\r\nFROM \"HEALTH_ADCS_RW_SPEED_CMD\"\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "IGRF_MOD_VEC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\r\n  \"Epoch_Time_Human\"::timestamp AS time,\r\n  \"IGRF_Mod_Vector_X\",\r\n  \"IGRF_Mod_Vector_Y\",\r\n  \"IGRF_Mod_Vector_Z\"\r\nFROM \"HEALTH_ADCS_IGRF_MOD_VEC\"\r\nORDER BY time;\r\n"
    }
   ]
  }
 ]
}