{
 "title": "OBC",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "title": "FSM State",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"FSM_State\"\nFROM\n  \"HEALTH_OBC\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time DESC\nLIMIT 5\n"
    }
   ]
  },
  {
   "title": "Number of Resets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Number_of_Resets\"\nFROM\n  \"HEALTH_OBC\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"IO_Errors\",\n  \"System_Errors\"\nFROM\n  \"HEALTH_OBC\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"CPU_Utilisation\"\nFROM\n  \"HEALTH_OBC\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Uptime\"\nFROM\n  \"HEALTH_OBC\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Reset Cause",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Reset_Cause\"\nFROM\n  \"HEALTH_OBC\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Rem_Heap",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"IRAM_Rem_Heap\",\n  \"ERAM_Rem_Heap\"\nFROM\n  \"HEALTH_OBC\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Task Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Task_Count\"\nFROM\n  \"HEALTH_OBC\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Task Status 59",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Task_59_Status\"\nFROM\n  \"HEALTH_OBC\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Tasl status 57",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Task_57_Status\"\nFROM\n  \"HEALTH_OBC\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Task Status 60",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Task_60_Status\"\nFROM\n  \"HEALTH_OBC\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Task Status 58",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "centraDB",
     "rawSql": "SELECT\n  \"Timestamp\"::timestamp AS time,\n  \"Task_58_Status\"\nFROM\n  \"HEALTH_OBC\"\nWHERE\n  $__timeFilter(\"Timestamp\"::timestamp)\nORDER BY\n  time DESC\nLIMIT 1\n"
    }
   ]
  }
 ]
}